language: python
python:
  - 2.7
addons:
  - sauce_connect:
    - username: $SAUCE_USERNAME
    - access_key: $SAUCE_ACCESS_KEY
install:
  - mkdir -p buildout-cache/downloads
# Keep the setuptools and zc.buildout versions in sync with travis.cfg.
# Or remove the -N (non-newest) from the buildout run in .travis.yml.
  - python bootstrap.py -c travis.cfg --buildout-version=2.5.0 --setuptools-version=19.6.2
  - bin/buildout -N -c travis.cfg annotate
  - bin/buildout -N -t 3 -c travis.cfg
script:
  - if [ "$BROWSER" != "code-analysis" ]; then export ROBOT_DESIRED_CAPABILITIES="$BROWSER,tunnel-identifier:$TRAVIS_JOB_NUMBER"; fi
  - if [ "$BROWSER" != "code-analysis" ]; then bin/test -vvv --all; fi
  - if [ "$BROWSER" == "code-analysis" ]; then bin/flake8 setup.py; fi
  - if [ "$BROWSER" == "code-analysis" ]; then bin/flake8 plone; fi
  - if [ "$BROWSER" == "code-analysis" ]; then bin/coverage run --source=plone.app.widgets --omit=plone/app/widgets/at_bbb.py,plone/app/widgets/dx_bbb.py,plone/app/widgets/dx_pac_bbb.py,plone/app/widgets/test\* bin/test --layer=\!PloneAppWidgetsLayer; fi
after_success:
  - bin/coveralls
env:
  matrix:
    - BROWSER="code-analysis"
    - BROWSER="platform:OS X 10.8,browserName:iphone,version:6.1,device-orientation:portrait"
    - BROWSER="platform:OS X 10.8,browserName:ipad,version:6.1,device-orientation:portrait"
    - BROWSER="platform:Linux,browserName:android,version:4.0,device-type:tablet,device-orientation:portrait"
    - BROWSER="platform:Windows 7,browserName:firefox,version:25"
    - BROWSER="platform:Windows 7,browserName:chrome,version:31"
    - BROWSER="platform:Windows 8.1,browserName:internet explorer,version:11"
    - BROWSER="platform:Windows 7,browserName:internet explorer,version:10"
    - BROWSER="platform:Windows 7,browserName:internet explorer,version:9"
    - BROWSER="platform:Windows 7,browserName:internet explorer,version:8"
    - BROWSER="platform:Windows 7,browserName:opera,version:12"
    - BROWSER="platform:OS X 10.8,browserName:safari,version:6"
  global:
    - secure: "X9AvF9DYKjG/E52ZKQGxxrMe/Z1FsuwJU9jk39NLia3aA3WyFKuE66BotqeZGi9Jk0V2IQWekMgZcAFIcRH6qbvMKcMtnhD+Wr8aiV7uby3wRjmPi2FznTiy+FvYwm8WiNBHw4Ek++nSCDkly0QGBUmJVvfe3zxNHSHSKx5E/yg="
    - secure: "CvB/BK4EhZIiruAuiIFw/Bn80Wv/5jGiS2tOCaXd54v7lhld2VBxyCfccIcizKlSkIXzDausw24zEF0HV4E6k4z8AB12h1DH/6p31+epbrvDnQOZ1Br2grusOqMbjOutRkJ0w+upI+BTaeSI9bmYXZQdpkLA5mJCv0sBbqi4SPA="
    - ROBOT_BUILD_NUMBER=plone.app.widgets-travis-$TRAVIS_BUILD_NUMBER
    - ROBOT_REMOTE_URL=http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub
matrix:
  allow_failures:
    - env: BROWSER="platform:OS X 10.8,browserName:iphone,version:6.1,device-orientation:portrait"
    - env: BROWSER="platform:OS X 10.8,browserName:ipad,version:6.1,device-orientation:portrait"
    - env: BROWSER="platform:Linux,browserName:android,version:4.0,device-type:tablet,device-orientation:portrait"
    - env: BROWSER="platform:Windows 8.1,browserName:internet explorer,version:11"
    - env: BROWSER="platform:Windows 7,browserName:internet explorer,version:10"
    - env: BROWSER="platform:Windows 7,browserName:internet explorer,version:9"
    - env: BROWSER="platform:Windows 7,browserName:internet explorer,version:8"
    - env: BROWSER="platform:Windows 7,browserName:opera,version:12"
    - env: BROWSER="platform:OS X 10.8,browserName:safari,version:6"
